Enhancement: Select First Day of Week for Locale
elementary/switchboard-plug-locale pull request #127
Opened 2020-11-12 20:55 UTC by lainsce

This eventually will change the order of days on Calendar and Date Time indicator popover by issuing a setting that gets read by both.

Looks like:
![Screenshot from 2020-11-12 17 53 56](https://user-images.githubusercontent.com/4886639/98995488-2f684880-2510-11eb-8b4d-f1d86865f229.png)

(P.S. Help I don't know what I'm doing :P)

2020-11-13 15:02 UTC, lainsce commented
The way this works is:

1. `io.elementary.switchboard.locale/first-day` changes, and sets a (translatable) string of the day that it is (`"Sunday"` is default)
2. This will propagate to whatever place reads this such as a calendar widget or some such, and reorders the columns to reflect the setting.
3. ???
4. Profit!

2020-11-13 18:53 UTC, lainsce commented
Oh, I just found out that using an int between 1 and 7 is what should be used since Posix methods do this for the first weekday. I'm going to change this to that.

2020-11-13 22:39 UTC, lainsce commented
Actually, going to need some help with save-stating this on the checkbox, as currently it jumps to Sunday.

2020-11-14 01:29 UTC, lainsce commented
Ready to review.

2020-11-17 17:48 UTC, jeremypw submitted a review, later dismissed
It is possible for `first_day` to take an invalid value and the combobox is then blank. 
When you select a different locale (but do not set it as default) and then close, `first_day` is set to `-1`. 
I think you should put a range attribute in the schema limiting acceptable entries 0 - 6. Should range check in the code when setting the combobox and when saving the setting as well.

I note that only one `first_day` can be saved so if someone needs to switch between two or more locales with different first days they would have to reset it each time. I guess if that is a significant issue it could be addressed in a later PR though.

2020-11-17 17:51 UTC, lainsce commented
Could you guide me on how to make a ranged gschema? I've never done that type of thing before.

As for the rest about checking on code if it's on the range, I'd wager it should be fixed if the gschema is ranged, wouldn't it?

2020-11-17 18:03 UTC, jeremypw commented on data/io.elementary.switchboard.locale.gschema.xml
> +		<key name="first-day" type="i">
To get a range, insert `<range min="0" max="6" /> here

2020-11-17 18:08 UTC, jeremypw commented
I am not quite sure what happens if code tries to write an out of range value to a setting so it is better to be sure this cannot happen one way or another.

2020-11-17 18:17 UTC, lainsce commented on data/io.elementary.switchboard.locale.gschema.xml
> +		<key name="first-day" type="i">
Alright.

2020-11-17 18:21 UTC, lainsce commented
There we go.

2020-11-17 18:45 UTC, jeremypw commented on src/LocaleManager.vala
> +            settings.set_int ("first-day", first_day);
Suggest `settings.set_int ("first-day", first_day.clamp (0, 6))`, then you do not need to range check elsewhere.

2020-11-17 18:46 UTC, jeremypw commented on src/Widgets/LocaleSetting.vala
> +            }
SImpler to range check in LocaleManager (see other comment)

2020-11-17 18:54 UTC, jeremypw commented on src/Widgets/LocaleSetting.vala
> +            first_day_combobox.changed.connect (compare);
Why not just call `compare ()` at the end of `on_first_day_changed ()`?  You could also rewrite `on_first_day_changed ()`` as a closure to make the code clearer:

```
first_day_combobox.changed.connect (() => {
     lm.set_user_first_day (first_day_combobo.active);
     compare ();
});

```

2020-11-17 18:54 UTC, jeremypw commented on src/Widgets/LocaleSetting.vala
> +        }
I dont think we need this function - just inline the return expression.

2020-11-17 18:54 UTC, jeremypw commented on src/Widgets/LocaleSetting.vala
> +            first_day_combobox.active = get_first_day ();
`get_first_day ()` references `first_day_combobox` so this is circular?  Should it be `first_day_combobox.active = lm.get_user_first_day ()`?

2020-11-17 19:18 UTC, lainsce commented on src/LocaleManager.vala
> +            settings.set_int ("first-day", first_day);
I see.

2020-11-17 19:26 UTC, lainsce commented
After addressing things, there's a small lag on first open, but shouldn't be anything bad.

2020-11-17 19:44 UTC, danrabbit commented on data/io.elementary.switchboard.locale.gschema.xml
> +		</key>
There is already precedent for this setting in Evolution at `/org/gnome/evolution/calendar/week-start-day-name`. We should probably be consistent in case we can pursue a desktop wide setting that GNOME will also agree on. They are use an enum with the names of the weekdays starting on `monday`

2020-11-17 20:01 UTC, lainsce commented on data/io.elementary.switchboard.locale.gschema.xml
> +		</key>
But if we do that, we'd need to ship the Evolution app, wouldn't we?

2020-11-17 20:04 UTC, lainsce commented on data/io.elementary.switchboard.locale.gschema.xml
> +		</key>
We could eventually rewrite if we could have the key without installing Evolution, I agree.

2020-11-17 20:05 UTC, 4jNsY6fCVqZv commented on src/Widgets/LocaleSetting.vala
> +            first_days.add (_("Thursday"));
I wonder under which circumstances it makes sense to offer the days Tuesday, Wednesday and Thursday here as an option. https://commons.wikimedia.org/wiki/File:First_Day_of_Week_World_Map.svg

2020-11-17 20:06 UTC, danrabbit commented on data/io.elementary.switchboard.locale.gschema.xml
> +		</key>
I'm saying this key should probably be structured in the same way, using an enum and using the name `week-start-day-name` etc so that if eventually there is a key in a shared component it will be easy to just change where we point gsettings instead of having to rewrite everything in a different format

2020-11-17 20:06 UTC, lainsce commented on src/Widgets/LocaleSetting.vala
> +            first_days.add (_("Thursday"));
I'm just using prior art from other implementations as a base for this, and all of them list all days.

2020-11-17 20:28 UTC, 4jNsY6fCVqZv commented on src/Widgets/LocaleSetting.vala
> +            first_days.add (_("Thursday"));
What other implementations are you referring to? 
And could you imagine to question their logic or even improve it? From the user's point of view it is not clear to me why I am offered this option.

2020-11-17 20:32 UTC, lainsce commented on data/io.elementary.switchboard.locale.gschema.xml
> +		</key>
Oh, I see.

I'll do that then.

2020-11-17 20:57 UTC, lainsce commented
After porting to a enum key, it seems that lag on first open vanished somehow :smile:

2020-11-18 18:42 UTC, jeremypw commented on src/Widgets/LocaleSetting.vala
> +            first_days.add (_("Thursday"));
I tend to agree that there is no reason to show users invalid entries in the combobox so marking this as unresolved so UX team can adjudicate.

The above chart shows a small island as having Friday as the first day but the underlying data table did not include it so it may not have a separate locale.

2020-11-18 18:51 UTC, lainsce commented on src/Widgets/LocaleSetting.vala
> +            first_days.add (_("Thursday"));
Another Prior Art I've found is with Calendar in Android, and in there only Monday, Friday, Saturday and Sunday are options. So I agree that maybe it's better to remove them instead of swamping the combobox with bogus options, like the data above shows, it's more common to have Monday, Saturday and Sunday as options..

2020-11-18 18:54 UTC, lainsce commented on src/Widgets/LocaleSetting.vala
> +            first_days.add (_("Thursday"));
So I'm going to remove the options that aren't matching real world use.

2020-11-18 19:02 UTC, lainsce commented
Removed the options that aren't matching real world use.

2020-11-19 16:11 UTC, jeremypw commented
I notice that all the monthly wall calendar images I've looked at for Maldives show Sunday as the leftmost column and the weekend as Friday/Saturday despite what Wikipedia says about Friday being the first day of the week :confused: However, I agree we should keep Friday as an option for now although how to interpret that in the Calendar widget might be tricky.

2020-11-19 16:21 UTC, jeremypw commented on src/Widgets/LocaleSetting.vala
> +            });
Now the combobox only contains 4 items, you can no longer use the active index as a proxy for the day number. You will have to e.g. have a two field store containing both the day name and the day number or find some other way of interconverting active index and day number

2020-11-19 16:36 UTC, lainsce commented on src/Widgets/LocaleSetting.vala
> +            });
> Have a two field store containing both the day name and the day number

I think this is the easiest to deal with, and minimal code movement.

2020-11-19 16:37 UTC, lainsce commented on src/Widgets/LocaleSetting.vala
> +            });
As the store isn't used in the key, the code is pointing at the index of the enum and syncing both.

2020-11-19 16:41 UTC, lainsce commented
Now the first day store stores both the index and name of the first day.

2020-11-20 11:40 UTC, jeremypw commented
I apologise - I forgot you had switched to storing the first day as an enum so in fact you do not need to store the day of the week as it is not used in this plug :disappointed:  You can revert the latest changes.  However, any app using this setting will have convert the enum to the appropriate day of week.

2020-11-20 11:59 UTC, jeremypw commented on src/Widgets/LocaleSetting.vala
> +            first_day_store.clear ();
Why do you need to rebuild the combobox when the locale changes? The contents of the box do not change.

2020-11-20 13:20 UTC, jeremypw commented
Just pushed a PR to this branch with a suggested simplification for you consideration.  It has the advantage that the value of the enum retrieved from the settings is already the correct day number so no conversion is required by client apps.

2020-11-20 17:39 UTC, lainsce commented
Yeah, that PR seems much more sane than what I was doing :P

2020-11-20 18:15 UTC, jeremypw commented
I think the code is now OK for storing a single global first-day. This is an improvement on the current situation where it is not possible to change the default first day at all.  A further enhancement would be for the correct first day to be automatically set according to the chosen locale. I guess this would mean creating and storing a table storing (or hard-coding) the correct first day for each locale available (or is there a library function for this??). However, this could be left for a further PR.

I'll flag this for UX input.

Need to block a further stable release until this setting actually has an effect on the calendar app.

2020-11-20 18:30 UTC, lainsce commented
> Need to block a further stable release until this setting actually has an effect on the calendar app.

There is a further PR involving the change applying to Calendar here: https://github.com/elementary/calendar/pull/638

And another one for the Date Time indicator here: https://github.com/elementary/wingpanel-indicator-datetime/pull/240

:smile:

2020-11-21 17:43 UTC, jeremypw commented
Yes, once this is merged I'll review those PRs.

2020-11-24 19:56 UTC, danrabbit requested changes

2020-11-24 19:56 UTC, danrabbit commented on data/io.elementary.switchboard.locale.gschema.xml
> +        <value nick='Saturday' value='6'/>
In the Evolution key, this starts with Monday. I also wonder if we might want to preserve `0` for a future automatic/locale option

2020-11-24 19:56 UTC, danrabbit commented on src/Widgets/LocaleSetting.vala
> +            content_area.attach (preview, 0, 6, 2, 1);
You don't need to specify length and width if they are 1
```suggestion
            content_area.attach (first_day_endlabel, 0, 4);
            content_area.attach (first_day_combobox, 1, 4);
            content_area.attach (preview, 0, 6, 2);
```

2020-11-24 19:56 UTC, danrabbit commented on src/Widgets/LocaleSetting.vala
> +                content_area.attach (temperature, 1, 5, 1, 1);
Same here
```suggestion
                content_area.attach (new EndLabel (_("Temperature:")), 0, 5);
                content_area.attach (temperature, 1, 5);
```

2020-11-24 20:03 UTC, danrabbit commented
> I guess this would mean creating and storing a table storing (or hard-coding) the correct first day for each locale available (or is there a library function for this??). However, this could be left for a further PR.

First week information is already stored in LC_TIME, but I have no idea how to read it. I can't seem to find anything on Valadoc about it. Maybe @tintou or @ryonakano knows

2020-11-24 21:34 UTC, lainsce commented on data/io.elementary.switchboard.locale.gschema.xml
> +        <value nick='Saturday' value='6'/>
Maybe it's better to just follow the Evolution key for now, with Monday=0, and maybe setting on Auto=7 later for less breakage.

2020-11-24 21:35 UTC, lainsce commented on src/Widgets/LocaleSetting.vala
> +            content_area.attach (preview, 0, 6, 2, 1);
Force of habit :sweat_smile:

2020-11-24 21:35 UTC, lainsce commented on src/Widgets/LocaleSetting.vala
> +                content_area.attach (temperature, 1, 5, 1, 1);
Force of habit :sweat_smile:

2020-11-24 21:37 UTC, lainsce commented
Review points addressed. :+1:

2020-11-25 16:11 UTC, jeremypw commented
If we can read the first day of the week from Posix then we do not really need a combobox ...

There a Posix enum NLTime.FIRST_WEEKDAY in posix.vapi - maybe this is useful?

2020-11-25 20:21 UTC, lainsce commented
The thing is that it's not really reading from Posix and automatically setting things, the problem this PR is solving; it's solving the "I'm Spanish, but my system is purposefully in English because I'm studying it or my company set it so, or whatever the reason, so calendars starts on Sunday instead of my country's week start. I can customize via the combobox to make it familiar to me, and keep using my system in English.".

2020-11-26 10:31 UTC, tintou commented on data/io.elementary.switchboard.locale.gschema.xml
> +        </key>
```suggestion
        <key name="week-start-day" type="s">
            <choices>
                <choice value='Locale'/>
                <choice value='Monday'/>
                <choice value='Friday'/>
                <choice value='Saturday'/>
                <choice value='Sunday'/>
            </choices>
            <default>'Locale'</default>
            <summary>Saves the First Day of the Week for use in locale settings such as a calendar display.</summary>
            <description>Saves the First Day of the Week for use in locale settings such as a calendar display. The 'Locale' value means to get the value from the current locale.</description>
        </key>
```
That's more something that I would consider. We should use the accountsservice to store this value for now anyway.

2020-11-26 12:15 UTC, lainsce commented on data/io.elementary.switchboard.locale.gschema.xml
> +        </key>
Wouldn't this be a next PR effort, to build a accountservices anything? I think it'll defocus and bloat this PR if I did the efforts of that here.

2020-11-26 12:16 UTC, lainsce commented on data/io.elementary.switchboard.locale.gschema.xml
> +        </key>
Same with a Locale option. That would be material for another PR.

2020-11-26 15:24 UTC, lainsce commented
Please understand that further efforts on Locale and Account Services or ideas like that would bloat this PR and make it not follow the (unwritten?) guideline of a PR doing one thing per PR as I was told many times to do.

2020-12-01 03:52 UTC, mcclurgm commented
I know this is out of scope, but since there's a discussion already here I don't know where better to put it. I put a bit of info about the posix locale [in the original issue](https://github.com/elementary/switchboard-plug-locale/issues/86#issuecomment-726339079). There's also some stuff about this over in the [calendar code](https://github.com/elementary/calendar/blob/4b7f3133bafa76e3c54596efd5e114ec15ce11dc/core/Services/Calendar/EventStore.vala#L300).

Also, there's a potential issue with the `WEEK_1STDAY` variable here. According to posix, the numbering of each day of the week depends on the value of that variable. So either we could take that into account here, or assert that every day of the week has the same number no matter what posix says. I put a comment to this effect in the Calendar PR.

2020-12-02 16:54 UTC, jeremypw commented
I am happy for this to be merged on the assumption that further work will be done to ensure that the default setting for this is correct.

2020-12-06 15:56 UTC, mcclurgm commented
I'm happy to do that since I did the week start stuff in calendar, but it will be a while before I can guarantee. But in theory a "correct" solution that accounts for the posix stuff should be pretty similar to what's in that codebase, assuming I did it right.

2020-12-06 16:28 UTC, jeremypw commented
Good - just needs to @danrabbit to sign off on it now.

2020-12-09 00:53 UTC, danrabbit commented
I feel like this should start at `1`, not `0` because as @mcclurgm points out in that calendar code block GLib uses 1-7 and we could reserve `0` for a future "automatic" setting

2020-12-09 01:03 UTC, lainsce commented
> I feel like this should start at `1`, not `0` because as @mcclurgm points out in that calendar code block GLib uses 1-7 and we could reserve `0` for a future "automatic/from locale" setting

But AFAIK, the Evolution key starts at 1 for Monday. So which futureproofing are we going to push towards?

2020-12-09 01:30 UTC, mcclurgm commented
> But AFAIK, the Evolution key starts at 1 for Monday. So which futureproofing are we going to push towards? 

Not sure what other future proofing you're referring to? It seems to me like matching Evolution would be a good thing.

I'd personally support changing to 1 = Monday, since then we could use it directly as a `GLib.Weekday` in any clients that access the setting. But if we change it, that will break what's in the active Calendar PR. (The current setting is equivalent to what's in all the Ubuntu locales I've seen, which is 1 = Sunday.) But it would simplify the code needed in Calendar, since it could just see the setting and immediately short-circuit with that result. (Basically, `this.week_start = (GLib.Weekday) setting; return;`)

2020-12-09 01:34 UTC, danrabbit commented
Yeah I think 1-7 starting with Monday seems like the best option since it matches Evolution and GLib.Weekday

2020-12-09 01:38 UTC, danrabbit requested changes

2020-12-09 01:38 UTC, danrabbit commented on data/io.elementary.switchboard.locale.gschema.xml
> +        <value nick='Sunday' value='6'/>
Based on discussion this should be:
```suggestion
        <value nick='Monday' value='1'/>
        <value nick='Friday' value='5'/>
        <value nick='Saturday' value='6'/>
        <value nick='Sunday' value='7'/>
```

2020-12-09 01:38 UTC, danrabbit commented on src/LocaleManager.vala
> +            settings.set_enum ("week-start-day-name", first_day.clamp (0, 6));
```suggestion
            settings.set_enum ("week-start-day-name", first_day.clamp (1, 7));
```

2020-12-09 01:38 UTC, danrabbit commented on src/Widgets/LocaleSetting.vala
> +            first_day_combobox.append ("6", _("Saturday"));
```suggestion
            first_day_combobox.append ("7", _("Sunday"));
            first_day_combobox.append ("1", _("Monday"));
            first_day_combobox.append ("5", _("Friday"));
            first_day_combobox.append ("6", _("Saturday"));
```

2020-12-09 13:18 UTC, lainsce commented
Alright, changes madded in. :)

2022-04-23 07:27 UTC, closed without merging